Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 45, in <module>
    from admissions_app import db, NoAdmissions, Config
ModuleNotFoundError: No module named 'admissions_app'
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 45, in <module>
    from admissions_app import db, NoAdmissions, Config
ModuleNotFoundError: No module named 'admissions_app'
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 45, in <module>
    from admissions_app import db, NoAdmissions, Config
ModuleNotFoundError: No module named 'admissions_app'
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 45, in <module>
    from admissions_app import db, NoAdmissions, Config
ModuleNotFoundError: No module named 'admissions_app'
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 45, in <module>
    from admissions_app import db, NoAdmissions, Config
ModuleNotFoundError: No module named 'admissions_app'
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 45, in <module>
    from admissions_app import db, NoAdmissions, Config
ModuleNotFoundError: No module named 'admissions_app'
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 45, in <module>
    from admissions_app import db, NoAdmissions, Config
ModuleNotFoundError: No module named 'admissions_app'
INFO:waitress:Serving on http://127.0.0.1:30440
DEBUG:listener:Webhook received: {}
DEBUG:listener:Webhook received: {}
DEBUG:listener:Webhook received: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'observation.add', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
DEBUG:listener:Webhook received: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'observation.add', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
DEBUG:listener:Webhook received: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'patient.admit', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
INFO:listener:New patient admission added: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'patient.admit', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
DEBUG:listener:Webhook received: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'patient.admit', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
ERROR:listener:Exception on /webhook [POST]
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: no_admissions.patientId

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 76, in webhook_listener
    db.session.add(new_entry)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2017, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1302, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1277, in _prepare_impl
    self.session.flush()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4341, in flush
    self._flush(objects)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4477, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4437, in _flush
    flush_context.execute()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: no_admissions.patientId
[SQL: INSERT INTO no_admissions ("facId", "patientId", "firstName", "lastName", gender, "birthDate", "admissionDate") VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('4', '11', None, None, None, None, '2015-04-23 17:53:18.543000')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
DEBUG:listener:Webhook received: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'patient.admit', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
ERROR:listener:Exception on /webhook [POST]
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: no_admissions.patientId

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 76, in webhook_listener
    db.session.add(new_entry)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2017, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1302, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1277, in _prepare_impl
    self.session.flush()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4341, in flush
    self._flush(objects)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4477, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4437, in _flush
    flush_context.execute()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: no_admissions.patientId
[SQL: INSERT INTO no_admissions ("facId", "patientId", "firstName", "lastName", gender, "birthDate", "admissionDate") VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('4', '11', None, None, None, None, '2015-04-23 17:53:18.543000')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
DEBUG:listener:Webhook received: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'patient.admit', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
ERROR:listener:Exception on /webhook [POST]
Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: no_admissions.patientId

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\Webhook Listener\listener.py", line 76, in webhook_listener
    db.session.add(new_entry)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2017, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1302, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1277, in _prepare_impl
    self.session.flush()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4341, in flush
    self._flush(objects)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4477, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 4437, in _flush
    flush_context.execute()
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\aburrows\Documents\Admissions_rocket_V1\venv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: no_admissions.patientId
[SQL: INSERT INTO no_admissions ("facId", "patientId", "firstName", "lastName", gender, "birthDate", "admissionDate") VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('4', '11', None, None, None, None, '2015-04-23 17:53:18.543000')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Database URI: sqlite:///C:\Users\aburrows\Documents\Admissions_rocket_V1\admissions_app\data/app.db
INFO:waitress:Serving on http://127.0.0.1:30440
DEBUG:listener:Webhook received: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'patient.admit', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
ERROR:listener:Error adding admission to database: (sqlite3.IntegrityError) UNIQUE constraint failed: no_admissions.patientId
[SQL: INSERT INTO no_admissions ("facId", "patientId", "firstName", "lastName", gender, "birthDate", "admissionDate") VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('4', '11', None, None, None, None, '2015-04-23 17:53:18.543000')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
DEBUG:listener:Webhook received: {'messageId': 'd0e584b9739f4e33a385d6aa20f6a7f2', 'eventType': 'observation.add', 'patientId': 11, 'orgId': 654, 'orgUuid': 'f88810ca-9e0c-4303-aaa4-bf387d6d8c26', 'facId': 4, 'eventDate': '2015-04-23T17:53:18.543Z', 'messageDate': '2015-04-23T18:58:57.382Z', 'resourceId': [23984]}
